<#
.SYNOPSIS
typdoc installer (PowerShell) for Windows — experimental.

.DESCRIPTION
Hosted at https://typdoc.thaitype.dev/install.ps1 and meant to be run with:

    irm https://typdoc.thaitype.dev/install.ps1 | iex

Hand-written rather than generated by cargo-dist's own PowerShell installer, for two independent
reasons found by actually reading that generated script's output against this repo:

  - It bakes one fixed version into itself at generation time, with no runtime version
    selection at all (no TYPDOC_VERSION-equivalent, no "latest" redirect) — incompatible with
    this being a single, permanently-hosted script that resolves a version every time it runs.
  - Its default install location is $env:CARGO_HOME/bin (or $HOME\.cargo\bin), not this
    project's fixed $env:LOCALAPPDATA\typdoc\bin — every generator must land on that exact path
    regardless of which one produced the script.

cargo-dist still builds and checksums the release archive this script downloads; only the
installer itself is hand-written.

Environment variables (end-user facing, see README/docs/getting-started.md):
  TYPDOC_VERSION   Install this exact release tag (e.g. "v0.3.1") instead of the latest one.
  INSTALL_DIR      Install into this directory instead of the default
                   ("$env:LOCALAPPDATA\typdoc\bin").

Environment variable for testing only — never documented anywhere else, and not a supported
interface: do not rely on this staying stable.
  TYPDOC_INSTALL_BASE_URL   Overrides the base URL the archive/checksum are fetched from, so CI
                            can point this script at a local HTTP server before any real release
                            exists yet. This comment (and the story's own contract) are this
                            variable's only documentation, on purpose.

This script never edits PATH, the registry, or any profile. If the install directory isn't
already on PATH, it prints the one line to run and exits 0 anyway — installation still
succeeded.
#>

$ErrorActionPreference = 'Stop'

$RepoOwner = 'thaitype'
$RepoName = 'typdoc'
$AppName = 'typdoc'

function Write-Info($message) {
    Write-Host $message
}

function Exit-WithError($message) {
    Write-Host "error: $message" -ForegroundColor Red
    exit 1
}

# Maps the running process's architecture to one of typdoc's release targets. Only
# x86_64-pc-windows-msvc is released; anything else (including arm64, which would otherwise run
# under x86_64 emulation) is reported as unsupported rather than silently substituted.
function Get-Target {
    $arch = [System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture
    switch ($arch) {
        'X64' { return 'x86_64-pc-windows-msvc' }
        default {
            Exit-WithError "unsupported platform: Windows on $arch has no prebuilt $AppName binary; see README for other install options"
        }
    }
}

function Get-Sha256($path) {
    return (Get-FileHash -Path $path -Algorithm SHA256).Hash.ToLowerInvariant()
}

function Main {
    $target = Get-Target
    $archiveName = "$AppName-$target.zip"

    $baseUrl = $env:TYPDOC_INSTALL_BASE_URL
    if (-not $baseUrl) {
        $baseUrl = "https://github.com/$RepoOwner/$RepoName"
    }

    # TYPDOC_VERSION pins an exact tag. Otherwise resolve "latest" via GitHub's own
    # releases/latest/download redirect — never the unauthenticated REST API, which is
    # rate-limited per-IP and collides across shared CI runners.
    if ($env:TYPDOC_VERSION) {
        $downloadPrefix = "$baseUrl/releases/download/$($env:TYPDOC_VERSION)"
    } else {
        $downloadPrefix = "$baseUrl/releases/latest/download"
    }

    $archiveUrl = "$downloadPrefix/$archiveName"
    $checksumUrl = "$archiveUrl.sha256"

    $tmpDir = Join-Path ([System.IO.Path]::GetTempPath()) ([System.Guid]::NewGuid())
    New-Item -ItemType Directory -Path $tmpDir | Out-Null
    try {
        $archivePath = Join-Path $tmpDir $archiveName
        $checksumPath = "$archivePath.sha256"

        Write-Info "downloading $AppName ($target) from $archiveUrl"
        try {
            Invoke-WebRequest -Uri $archiveUrl -OutFile $archivePath -UseBasicParsing
        } catch {
            Exit-WithError "failed to download $archiveUrl"
        }
        try {
            Invoke-WebRequest -Uri $checksumUrl -OutFile $checksumPath -UseBasicParsing
        } catch {
            Exit-WithError "failed to download $checksumUrl"
        }

        $checksumLine = (Get-Content -Path $checksumPath -TotalCount 1)
        if (-not $checksumLine) {
            Exit-WithError "checksum file at $checksumUrl was empty or unreadable"
        }
        $expected = ($checksumLine -split '\s+')[0].ToLowerInvariant()
        $actual = Get-Sha256 $archivePath

        if ($expected -ne $actual) {
            Exit-WithError "checksum mismatch for $archiveName`n  expected: $expected`n  actual:   $actual`nnothing was installed."
        }

        $extractDir = Join-Path $tmpDir 'extracted'
        Expand-Archive -Path $archivePath -DestinationPath $extractDir

        # The archive's own top-level folder (e.g. typdoc-x86_64-pc-windows-msvc/) is the only
        # entry under $extractDir; the binary lives one level inside it.
        $innerDir = Get-ChildItem -Path $extractDir -Directory | Select-Object -First 1
        if (-not $innerDir) {
            Exit-WithError "archive did not contain the expected '$AppName.exe' binary"
        }
        $binSrc = Join-Path $innerDir.FullName "$AppName.exe"
        if (-not (Test-Path $binSrc)) {
            Exit-WithError "archive did not contain the expected '$AppName.exe' binary"
        }

        if ($env:INSTALL_DIR) {
            $installDir = $env:INSTALL_DIR
        } else {
            $installDir = Join-Path $env:LOCALAPPDATA "$AppName\bin"
        }

        New-Item -ItemType Directory -Path $installDir -Force | Out-Null
        Copy-Item -Path $binSrc -Destination (Join-Path $installDir "$AppName.exe") -Force

        Write-Info "installed $AppName to $(Join-Path $installDir "$AppName.exe")"

        $pathEntries = ($env:Path -split ';') | Where-Object { $_ -ne '' }
        $onPath = $pathEntries | Where-Object { $_.TrimEnd('\') -ieq $installDir.TrimEnd('\') }
        if (-not $onPath) {
            Write-Info ""
            Write-Info "$installDir is not on your PATH. Add it by running:"
            Write-Info ""
            Write-Info "    `$env:Path = `"$installDir;`$env:Path`""
        }
    } finally {
        Remove-Item -Path $tmpDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Main
